### ISSUE TITLE
Preview Builds in PR for NuGet?

### ISSUE THREAD

**Issue by BenjaminAbt** [dotnet/nbgv#27]
I switched from GitVersion to GitVersioning and I love it. Thanks for all your work!

I use this GitHub Action snippet

```yaml
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
      
      - uses: aarnott/nbgv@v0.3 # https://github.com/AArnott/nbgv
        id: nbgv

      - name: Versioning
        run: echo ${{ steps.nbgv.outputs.SemVer2 }}

      - name: Build with dotnet
        run: dotnet build
              --configuration ${{ env.BuildConfig }}
              /p:Version=${{ steps.nbgv.outputs.AssemblyVersion }}

      - name: Test with dotnet
        run: dotnet test 

      - name: Pack NuGet
        run: dotnet pack 
              --configuration ${{ env.BuildConfig }}
              /p:Version=${{ steps.nbgv.outputs.NuGetPackageVersion }}
```

For the NuGet currently it creates for example version `3.2.1` no matter if I am directly on the master or in a pull request. Shouldn't something like `3.2.1-pr<PR Id>.<Build Id>` be created in the Pull Request?
