### ISSUE TITLE
nbgv is broken with now that the `add-path` command is disabled

### ISSUE THREAD

**Issue by jamesmcguirepro** [dotnet/nbgv#33]
```
Error: Unable to process command '::add-path::C:\Users\runneradmin\.dotnet\tools' successfully.
Error: The `add-path` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```

**Comment by AArnott** [comment]
Duplicate of #32

Please attach links to your GitHub workflow executions so we can investigate the logs and find out why the existing fix for this isn't resolving it for your case.

**Comment by jamesmcguirepro** [comment]
Unfortunately, it's a private repo.  I did attach the output of the command.  Here's how we are calling it:
```
      # Use Nerdbank.GitVersioning to set version variables: https://github.com/dotnet/nbgv
      - name: Use Nerdbank.GitVersioning to set version variables
        uses: dotnet/nbgv@v0.3.1
        with:
          setAllVars: true
```

I think #32 and https://github.com/dotnet/Nerdbank.GitVersioning/pull/516 fixed the calls to the `set-env` command.

However, `add-path` is a separate command.  

I don't know typescript very well, but if I had to guess, this could be a cause:  https://github.com/dotnet/nbgv/blob/master/src/main.ts#L21
